name: MagicBlock
version: '3.2.0.1'
main: io.github.syferie.magicblock.MagicBlockPlugin
api-version: '1.18'
authors: [Syferie]
description: A plugin that allows players to use magic blocks with limited uses.
softdepend: [PlaceholderAPI]
folia-supported: true

commands:
  magicblock:
    description: MagicBlock main command
    aliases: [mb]
    usage: /<command> [args]

permissions:
  magicblock.admin:
    description: Allows access to all MagicBlock commands and features
    default: op
    children:
      magicblock.use: true
      magicblock.break: true
      magicblock.get: true
      magicblock.give: true
      magicblock.reload: true
      magicblock.settimes: true
      magicblock.addtimes: true
      magicblock.getfood: true
      magicblock.list: true
      magicblock.performance: true
  magicblock.use:
    description: Allows placing and interacting with MagicBlocks (does not include breaking)
    default: true
  magicblock.break:
    description: Allows breaking MagicBlocks
    default: true
  magicblock.get:
    description: Allows getting MagicBlocks
    default: op
  magicblock.give:
    description: Allows giving MagicBlocks to other players
    default: op
  magicblock.reload:
    description: Allows reloading the plugin configuration
    default: op
  magicblock.settimes:
    description: Allows setting use times for MagicBlocks
    default: op
  magicblock.addtimes:
    description: Allows adding use times to MagicBlocks
    default: op
  magicblock.getfood:
    description: Allows getting magic food items
    default: op
  magicblock.list:
    description: Allows viewing bound blocks list
    default: true
  magicblock.performance:
    description: Allows viewing plugin performance reports
    default: op